[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "irca-sdk"
version = "0.3.0"
description = "Official Python SDK for the IRC-A (Internet Relay Chat for Agents) protocol with FAISS semantic routing."
readme = "README.md"
authors = [
    { name = "Sandro Garcia" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "fastapi",
    "uvicorn",
    "httpx",
    "python-dotenv",
    "a2a-sdk",
    "numpy",
    "faiss-cpu",
    "pydantic",
    "fastmcp",
    "pyyaml",
    "mangum",
    "openai",
    "pyjwt",
    "cryptography"
]
requires-python = ">=3.10"

[project.optional-dependencies]
local = [
    "sentence-transformers"
]

[project.scripts]
irc-a-gateway = "irca_sdk.core.gateway:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["irca_sdk*", "bfa_sdk*"]

[tool.pytest.ini_options]
pythonpath = ["."]

